wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    code_path: code/one_pixel_vit.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1662640994
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      2:
      - 1
      - 41
      - 49
      - 55
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
